#!/usr/bin/env node
// Build-time script: fetch a real, openly-licensed CEFR-graded wordlist and emit
// a bundled TS file (src/data/cefrWords.ts) the app reads directly. No AI, no
// runtime network — the vocabulary is genuinely CEFR-valid because it comes from
// the Open Language Profiles / CEFR-J datasets.
//
// Source (CC BY-SA 4.0 — attribution preserved in the generated file):
//   English Vocabulary Profile (CEFR-J)  A1–B2
//   Octanove Vocabulary Profile          C1–C2
//   https://github.com/openlanguageprofiles/olp-en-cefrj
//
// Usage: node scripts/fetch-cefr.mjs

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const BASE = 'https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master';
const SOURCES = [
  `${BASE}/cefrj-vocabulary-profile-1.5.csv`,          // A1, A2, B1, B2
  `${BASE}/octanove-vocabulary-profile-c1c2-1.0.csv`,  // C1, C2
];

// CEFR band → numeric level (1..6).
const CEFR_TO_LEVEL = { A1: 1, A2: 2, B1: 3, B2: 4, C1: 5, C2: 6 };

async function fetchCsv(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  return res.text();
}

// Normalize a raw headword to a single clean word, or null to drop it.
function cleanWord(raw) {
  // Take the first slash-variant: "adviser/advisor" -> "adviser".
  let w = raw.split('/')[0].trim().toLowerCase();
  // Drop multi-word entries (games work on single words) and anything with
  // non-letter characters except an internal hyphen.
  if (!/^[a-z]+(?:-[a-z]+)*$/.test(w)) return null;
  if (w.length < 2) return null;
  return w;
}

async function main() {
  const byWord = new Map(); // word -> lowest level seen

  for (const url of SOURCES) {
    const csv = await fetchCsv(url);
    const lines = csv.split(/\r?\n/);
    const header = lines[0].split(',');
    const hwIdx = header.indexOf('headword');
    const cefrIdx = header.indexOf('CEFR');
    if (hwIdx < 0 || cefrIdx < 0) throw new Error(`Unexpected columns in ${url}: ${header}`);

    for (const line of lines.slice(1)) {
      if (!line) continue;
      const cols = line.split(','); // no quoted commas in these files (verified)
      const word = cleanWord(cols[hwIdx] ?? '');
      const level = CEFR_TO_LEVEL[(cols[cefrIdx] ?? '').trim()];
      if (!word || !level) continue;
      // Lowest level wins — a word introduced at A2 shouldn't also sit in C1.
      const prev = byWord.get(word);
      if (prev === undefined || level < prev) byWord.set(word, level);
    }
  }

  const words = [...byWord.entries()]
    .map(([word, level]) => ({ word, level }))
    .sort((a, b) => (a.level - b.level) || a.word.localeCompare(b.word));

  const counts = {};
  for (const { level } of words) counts[level] = (counts[level] ?? 0) + 1;

  const banner = `// AUTO-GENERATED by scripts/fetch-cefr.mjs — do not edit by hand.
// Source: Open Language Profiles (English Vocabulary Profile / CEFR-J + Octanove),
// licensed CC BY-SA 4.0 — https://github.com/openlanguageprofiles/olp-en-cefrj
// Levels: 1=A1 2=A2 3=B1 4=B2 5=C1 6=C2. ${words.length} words total.`;

  const body = `${banner}

// Level is a plain number (1..6) rather than a 1|2|..|6 literal union: with
// thousands of entries the union is too complex for TS to represent (TS2590).
export type CefrLevel = number;

export interface CefrWord { word: string; level: CefrLevel; }

export const CEFR_WORDS: CefrWord[] = [
${words.map((w) => `  { word: ${JSON.stringify(w.word)}, level: ${w.level} },`).join('\n')}
];
`;

  const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data');
  const outFile = join(outDir, 'cefrWords.ts');
  await writeFile(outFile, body, 'utf8');

  console.log(`Wrote ${outFile}`);
  console.log(`${words.length} words. Per level:`,
    Object.entries(counts).map(([l, n]) => `L${l}:${n}`).join('  '));
}

main().catch((e) => { console.error(e); process.exit(1); });
