-- Invite codes, so a Pro user can create a private team and let people in.
--
-- One rotating code per team rather than a row per invitee: a teacher hands the
-- same code (or link) to a whole class, and regenerating it revokes every link
-- that was ever shared — which is the operation you actually want when a code
-- ends up somewhere it shouldn't. Per-person invites with expiry can be added
-- later without disturbing this; they'd be a separate table.
--
-- The code is generated by the `teams` edge function, which is also where
-- "creating a team requires Pro" and "only the owner may rotate" are enforced.

alter table teams
  add column if not exists invite_code text unique;

-- Built-in teams (Global) are joined by anyone and never carry a code.
