-- Doodles get their own table, off `word_cache`.
--
-- They used to live in `word_cache.doodle`, which meant a doodle could only be
-- saved for a word that already had a cache row — i.e. one whose definition
-- had been generated by someone. Doodle sheets deliberately batch in the words
-- a learner is about to see, and those are mostly words nobody has generated
-- yet, so the write matched no row and the doodle was silently dropped: paid
-- for, shown once from the browser's localStorage, then redrawn from scratch
-- for the next user (see the "cache write matched NO row" warning in the `ai`
-- function). Keyed on its own table, every doodle we pay for persists for
-- everyone, whether or not the word has been generated yet.
create table if not exists word_doodles (
  word text primary key,            -- English seed word, lowercased
  doodle text not null,             -- small data: URI thumbnail (keyed-out background)
  created_at timestamptz not null default now()
);

-- Carry over everything already drawn so nothing gets paid for twice.
insert into word_doodles (word, doodle)
  select word, doodle from word_cache where doodle is not null
  on conflict (word) do nothing;

-- Same posture as word_cache: RLS on with no policies, so only the service
-- role (the `ai` edge function) can read or write. Clients get doodles through
-- the function, never straight from the table.
alter table word_doodles enable row level security;

-- `word_cache.doodle` is deliberately left in place: it is now unread, but
-- keeping it means this migration is reversible without data loss. Drop it in
-- a later migration once the new table has proven itself in production.
